recipe_catalogue/recipe_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('', RedirectView.as_view(url='recipes/')),

    # import django's authentication system
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_catalogue/recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('add_additional_ingredients/<int:pk>',
         views.add_additional_ingredients, name='add_additional_ingredients'),
    path('recipe_detail/<int:pk>',
         views.RecipeDetail.as_view(), name='recipe_detail'),
    path('private_feed/', views.private_feed, name='private_feed'),
]

recipe_catalogue/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),
    path('user_profile/', views.user_profile, name='user_profile'),
]

recipe_catalogue/recipes/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

os.pardir


def recipe_image_file_path(instance, filename):
    '''Generate filepath for new recipe_image'''
    ext = os.path.splitext(filename)[1]
    filename = f"{uuid4()}{ext}"
    return os.path.join('uploads', 'recipe', filename)


class Recipe(models.Model):

    recipe_name = models.CharField(max_length=200)
    recipe_image = models.ImageField(upload_to=recipe_image_file_path)

    MEAL_TIME_CHOICES = [
        ('b', 'Breakfast'),
        ('l', 'Lunch'),
        ('d', 'Dinner'),
        ('s', 'Snack'),
    ]
    meal_time = models.CharField(
        max_length=1, choices=MEAL_TIME_CHOICES, default='b')

    ingredients = models.ManyToManyField('Ingredient')

    COST_CHOICES = [
        ('1', '£'),
        ('2', '££'),
        ('3', '£££'),
        ('4', '££££'),
    ]
    cost = models.CharField(max_length=1, choices=COST_CHOICES, default='1')

    instructions = models.TextField(max_length=800)

    DIFFICULTY_CHOICES = [
        ('e', 'Easy'),
        ('m', 'Medium'),
        ('d', 'Difficult'),
        ('p', 'Pro'),
    ]
    difficulty_level = models.CharField(max_length=1,
                                        choices=DIFFICULTY_CHOICES,
                                        default='e')

    tags = models.ManyToManyField('Tag')
    recipe_author = models.ForeignKey(User, on_delete=models.CASCADE)
    uploaded_date = models.DateField(auto_now_add=True)

    VISIBILITY_CHOICES = [
        ('pu', 'Public'),
        ('pr', 'Private'),
    ]
    visibility = models.CharField(
        max_length=2, choices=VISIBILITY_CHOICES, default='pu')

    def __str__(self):
        return self.recipe_name


class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=30, unique=True)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ['ingredient_name']

    def __str__(self):
        return self.ingredient_name


class Tag(models.Model):
    tag_name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ['tag_name']

    def __str__(self):
        return self.tag_name

recipe_catalogue/recipes/forms.py
from django import forms
from django.forms import ModelForm
from . import models


class AddRecipeForm(ModelForm):
    # recipe_name = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))

    class Meta:
        model = models.Recipe
        fields = ('recipe_name', 'recipe_image', 'meal_time',
                  'ingredients', 'cost', 'instructions',
                  'difficulty_level', 'tags', 'recipe_author', 'visibility')

        widgets = {
            'recipe_name': forms.TextInput(attrs={'class': 'form-control'}),
            'recipe_image': forms.FileInput(attrs={'class': 'form-control-file'}),
            'meal_time': forms.RadioSelect(attrs={'class': 'InLineRadios'}),
            'ingredients': forms.CheckboxSelectMultiple(attrs={'class': 'InlineRadios'}),
            'cost': forms.RadioSelect(attrs={'class': 'InlineRadios'}),
            'instructions': forms.Textarea(attrs={'class': 'form-control'}),
            'difficulty_level': forms.RadioSelect(attrs={'class': 'InlineRadios'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'InlineRadios'}),
            'recipe_author': forms.HiddenInput(attrs={'class': 'form-control'}),
            'visibility': forms.RadioSelect(attrs={'class': 'InlineRadios'}),
        }

        labels = {
            'ingredients': 'Ingredients: (Note, more ingredients can be added on the subsequent page)',
            'instructions': 'Recipe method:',
            'tags': 'Tags: (Note, more tags can be added on the subsequent page)',
        }


class AddIngredientForm(ModelForm):

    class Meta:
        model = models.Ingredient
        fields = ('ingredient_name', 'user')

recipe_catalogue/recipes/views.py
from django.shortcuts import render, redirect
from .models import Recipe, Ingredient
from .forms import AddRecipeForm, AddIngredientForm
from django.forms import inlineformset_factory
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.http import HttpResponse

# Create your views here.


def index(request):
    all_recipes = Recipe.objects.exclude(visibility__exact='pr').all()
    context = {'recipes': all_recipes}

    return render(request, 'recipes/index.html', context=context)


@login_required
def private_feed(request):
    users_recipes = Recipe.objects.filter(recipe_author__exact=request.user)
    context = {'recipes': users_recipes}

    return render(request, 'recipes/private_feed.html', context)


@login_required
def add_recipe(request):
    if request.method == "POST":
        form = AddRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save()
            messages.success(request, "Your recipe was successfully added!")

            print(recipe.pk)
            return redirect('add_additional_ingredients', recipe.pk)
    else:
        form = AddRecipeForm(initial={'recipe_author': request.user})

    return render(request, 'recipes/add_recipe.html', {'form': form})


@login_required
def add_additional_ingredients(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    form = AddIngredientForm()
    if request.method == 'POST':
        form = AddIngredientForm(request.POST)
        if form.is_valid():
            ingredient = form.save()
            recipe.ingredients.add(ingredient)
            return redirect('add_additional_ingredients', recipe.pk)

    context = {'form': form, 'recipe': recipe}

    return render(request, 'recipes/add_additional_ingredients.html', context)


class RecipeDetail(DetailView):
    model = Recipe

recipe_catalogue/recipes/templates/recipes/add_additional_ingredients.html
{% extends 'base.html' %}
{% block  content %}



{{ context }}

{{recipe.recipe_name}}




<main>
        <div class="registration-form">
            <h1 class="h3 mb-3 fw-normal">Add additional ingredients:</h1>
            
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissibile fade show alert-register" role="alert">
                    There was an error with your form...
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}


                <button class="btn btn-secondary w-100 py-2" type="submit" value="signup">Add another ingredient?</button>
            </form>

            <button class="btn btn-primary w-100 py-2" type="submit" value="signup">
                <a href={% url 'home' %} class="view-recipe-text">Create Recipe</a>
            </button>


        </div>    
</main>



{% endblock %}

recipe_catalogue/recipes/templates/recipes/add_recipe.html
{% extends 'base.html' %}
{% block  content %}

<main>
        <div class="registration-form">
            <h1 class="h3 mb-3 fw-normal">Add new recipe:</h1>
            
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissibile fade show alert-register" role="alert">
                    There was an error with your form...
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}
            
                <button class="btn btn-primary w-100 py-2" type="submit" value="signup">Submit</button>
            </form>
        </div>    
</main>



{% endblock %}

recipe_catalogue/recipes/templates/recipes/index.html
{% extends 'base.html' %}
{% block  content %}

<div>
</div>

<div class="album py-5 bg-body-tertiary">
    
    <div class="container">
        
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for recipe in recipes %}
                
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{recipe.recipe_image.url}}" width="100%" height="255" object-fit="cover">
                    <div class="card-body increase_card_text_padding">
                        <p class="card-text reduce_bottom_margin">{{recipe.recipe_name}}</p>
                        <div class="d-flex justify-content-between align-items-center" style="font-size: 14px;">
                            <p class="text-body-secondary reduce_bottom_margin">{{recipe.get_difficulty_level_display}}</p>
                            <p class="text-body-secondary reduce_bottom_margin">{{recipe.get_cost_display}}</p>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-body-secondary">Uploaded by: <span class="recipe-card-author">{{recipe.recipe_author}}</span></small>
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary view-recipe-btn">
                                    <a href="{% url 'recipe_detail' recipe.pk %}" class="view-recipe-text">
                                        View
                                    </a>
                                </button>
                            </div>                                
                        </div>
                    </div>
                </div>
            </div>
            
            {% endfor %}
                    
        </div>
    
    </div>

</div>

{% endblock  %}

recipe_catalogue/recipes/templates/recipes/private_feed.html
{% extends 'base.html' %} {% block content %}

<div></div>

<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for recipe in recipes %}

      <div class="col">
        <div class="card shadow-sm">
          <img
            src="{{recipe.recipe_image.url}}"
            width="100%"
            height="255"
            object-fit="cover"
          />
          <div class="card-body increase_card_text_padding">
            <p class="card-text reduce_bottom_margin">
              {{recipe.recipe_name}} - {{recipe.get_visibility_display}} Recipe
            </p>
            <div
              class="d-flex justify-content-between align-items-center"
              style="font-size: 14px"
            >
              <p class="text-body-secondary reduce_bottom_margin">
                {{recipe.get_difficulty_level_display}}
              </p>
              <p class="text-body-secondary reduce_bottom_margin">
                {{recipe.get_cost_display}}
              </p>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-body-secondary"
                >Uploaded by:
                <span class="recipe-card-author"
                  >{{recipe.recipe_author}}</span
                ></small
              >
              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-sm btn-outline-secondary view-recipe-btn"
                >
                  <a
                    href="{% url 'recipe_detail' recipe.pk %}"
                    class="view-recipe-text"
                  >
                    View
                  </a>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

recipe_catalogue/recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% block  content %}
    <div class="container">
        <!-- Content Start -->
        <article class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <div class="flex-col">
                <h1 class="title top-margin">{{ recipe.recipe_name }}</h1>
                <div class="flex-row">
                    <div class="flex-row top-margin">
                        <img src="{{ recipe.recipe_image.url }}" class="main-detail-image">
                    </div>
                </div>
                <div class="post-meta flex-row-space-between top-margin">
                    <div class="">
                        <span><span class="bold">Uploaded by:</span> {{ recipe.recipe_author }}</span>
                    </div>
                    <div class="">
                        <span><span class="bold">Mealtime:</span> {{ recipe.get_meal_time_display }}</span>
                    </div>
                    <div class="">
                        <span><span class="bold">Cost:</span> {{ recipe.get_cost_display }}</span>
                    </div>
                    <div class="">
                        <span><span class="bold">Difficulty:</span> {{ recipe.get_difficulty_level_display }}</span>
                    </div>
                    <div class="">
                        <span><span class="bold">Uploaded Date:</span> {{ recipe.uploaded_date }}</span>
                    </div>
                </div>
                <div class="post-content top-margin">
                    <div class="recipe-ingredients">
                        <h2>Ingredients</h2>
                        <ul class="ct-list">
                            {% for ingredient in recipe.ingredients.all %}<li>{{ ingredient }}</li>{% endfor %}
                        </ul>
                    </div>
                    <div class="recipe-instructions">
                        <h2>Instructions</h2>
                        {{ recipe.instructions|linebreaks }}
                    </div>
                </div>
            </div>
        </article>
        <!-- Content End -->
    {% endblock %}